config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }


  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end


  root 'public/homes#top'
  get 'about' => 'public/homes#about'


  namespace :admin do
   resources :tags
   resources :posts
   resources :jobs
   resources :users
  end
  scope module: :public do
   resources :tags

   resources :jobs
   resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
   end
   resources :targets
   resources :steps
   resources :posts do
    resources :post_tags
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
   end


  end



  #devise_for :admins
  #devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
  belongs_to :post
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments
  has_many :image_tags, dependent: :destroy

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  enum status: { secret: 0, disclosure: 1 }
  #has_many :comments
  #has_many :favorites
  has_one_attached :image
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :user
  def self.chart_date
    order(date: :asc).pluck('date', 'count').to_h
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
 has_many :post_tags, dependent: :destroy
 has_many :posts, through: :post_tags ,dependent: :destroy
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user

  enum status: { process: 0, success: 1 , failed: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :steps
  has_many :targets
  belongs_to :job, optional: true
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  enum gender: { ignore: 0, men: 1, women: 2 }
  enum status: { secret: 0, disclosure: 1 }
  #has_many :comments
  #has_many :favorites
  has_one_attached :profile_image
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  def fair_weight
  height * height * 22 / 10000
  end
  def bmi
    weight * 10000 / height / height 
  end
  def bmi25
    height * height * 25 / 10000
  end
  def bmi30
    height * height * 30 / 10000
  end
  def bmi35
    height * height * 35 / 10000
  end
  def bmi40
    height * height * 40 / 10000
  end
  def bmi18
    height * height * 37 / 20000
  end
  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @jobs = Job.all
    @job = Job.new
  end

  def new
  end

  def show
    @job = Job.find(params[:id])
  end
  def create
   @job = Job.new(job_params)
    if @job.save
     redirect_to jobs_path
    else
      render :index
    end
  end
  private
  def job_params
    params.require(:job).permit(:name)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end
  
  def destroy
   post = Post.find(params[:id])
   post.destroy
   redirect_to admin_posts_path
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def show
    @tag = Tag.find(params[:id])
  end
  
  def create
   @tag = Tag.new(tag_params)
    if @tag.save
     redirect_to admin_tags_path
    else
      render :index
    end
  end
  
  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @user = User.find(params[:id])
    @step = Step.new
    @steps = @user.steps
    @targets = @user.targets
  end
  

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(10)
  end
  
  def destroy
   user = User.find(params[:id])
    if user_id == current_user.id
       user.destroy 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/jobs/edit.html.erb
<h1>Admin::Jobs#edit</h1>
<p>Find me in app/views/admin/jobs/edit.html.erb</p>

app/views/admin/jobs/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-md-5">
      <h2>ステータス一覧</h2>

       <table class='table mt-3'>
         <thead>
           <th>ステータスID</th>
           <th>ステータス名</th>
         </thead>
         <tbody>
           <% @jobs.each do |job| %>
           <tr>
             <td><%= job.id %></td>
             <td><%= job.name %></td>
           </tr>
           <% end %>
         </tbody>
       </table>
      </div>
      <div class="col-md-5">ステータスを追加
         <%= form_with model: @job, url: admin_jobs_path, class: "d-flex align-items-center" do |f| %>
         <%= render 'layouts/errors', model: f.object %></br>
          <div class="ml-3"><%= f.label :name, "ステータス名", class: "small" %></div>
          <div class="ml-3"><%= f.text_field :name, placeholder: "ステータス名" %></div>
          <div class="ml-2"><%= f.submit "新規登録", class: "form-control btn btn-success ml-5" %></div>
         <% end %>
       </div>
    </div>
</div>

app/views/admin/jobs/new.html.erb
<h1>Admin::Jobs#new</h1>
<p>Find me in app/views/admin/jobs/new.html.erb</p>

app/views/admin/jobs/show.html.erb
<div class="container">
  <div class="row mb-4">
    
    <div class="col-md-7">
      <h3 class="offset-1 my-5 text title-text">会員一覧（<%= @job.name %>）</h3>
      <div class="row">
        <div class="col-12 mx-auto">
          

          <table class="table table-hover">
            <thead>
              <tr class="table-active text">
                <th>氏名</th>
                <th>ステータス</th>
                <th>投稿数</th>
                <th></th>
                <th></th>
              </tr>
            </thead>

              <tbody>
                <% @job.users.each do |user| %>
                 <% if user.status == "disclosure" %>
                  <tr class="light-text">
                    <td class="text">
                      <%= link_to admin_user_path(user), class: "text-dark" do %>
                        <%= user.name %>
                      <% end %>
                    </td>
                    <td>
                      <%= user.job.name %>
                    </td>
                    <td>
                      <%= user.posts.count %>件
                    </td>
                    
                  </tr>
                  <% end %>
                <% end %>
              </tbody>
           </table>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-sm-7 mx-auto">
      <h2>投稿一覧</h2>

      <% unless @posts.blank? %>
       <table class='table mt-3'>
         <thead>
           <th></th>
           <th>タイトル</th>
           <th></th>
         </thead>
         <tbody>
           <% @posts.each do |post| %>
           <% if post.status == "disclosure" %>
           <tr>
             <td>
                 <%= link_to admin_post_path(post) do %>
                 <%= image_tag post.get_image, size:'50x50' %><% end %>
             </td>
             <td><%= link_to post.title, admin_post_path(post) %></td>
             <td><%#= link_to "削除する", post, url: admin_posts_path, method: :delete, data: { confirm: '本当にかまいませんか？' }, class: "btn btn-danger ml2" %></td>
           <% end %></tr>
           <% end %>
         </tbody>
       </table>
       <% else %>
        <p>投稿はありません</p>
       <% end %>

      <div class= "d-flex justify-content-center">

      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container pt-5">
   <div class="row">
	   
	     <div class="content col-md-7">
		     <h2 class="section-ttl"><%= @post.title %></h2>
		       <div class="flex text-center">
		         <%# if @post.image.attached? %>
		   	     <%= image_tag @post.getimage, size: "400x300" %>
		   	     <%# else %>
		   	     <%#= image_tag 'no_image', size: "400x300" %>
             <%# end %>
		       </div></br>
		       <div class="post_info text-right">
		   	     作成者　<%= @post.user.name %></br>
		   	     <%= @post.count %>歩</br>
		       </div>
		       <div class="pt-3 pl-5">
		   	      <%= @post.body %>
		       </div></br>
		       <div class="text-right pt-4">
		   	   <div class="text-info">タグ　　　</div>
		       <% @post.tags.each do |tag| %>
             <%= tag.name %>
           <% end %></div>
		       <div class="text-right">
		       	
		           <%#= link_to "削除する", @post, url: admin_posts_path ,method: :delete, data: { confirm: '本当にかまいませんか？' }, class: "btn btn-danger ml2" %>
		   	      
		      	
		       

	   
</div>
</div>

app/views/admin/tags/edit.html.erb
<h1>Admin::Tags#edit</h1>
<p>Find me in app/views/admin/tags/edit.html.erb</p>

app/views/admin/tags/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-md-5">
      <h2>タグ一覧</h2>

       <table class='table mt-3'>
         <thead>
           <th>タグID</th>
           <th>タグ名</th>
           <th></th>
         </thead>
         <tbody>
           <% @tags.each do |tag| %>
           <tr>
             <td><%= tag.id %></td>
             <td><%= tag.name %></td>
             <td><%#= link_to 'Destroy', tag, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
           </tr>
           <% end %>
         </tbody>
       </table>
      </div>
      <div class="col-md-5">タグを追加
         <%= form_with model: @tag, url: admin_tags_path, class: "d-flex align-items-center" do |f| %>
         <%= render 'layouts/errors', model: f.object %></br>
          <div class="ml-3"><%= f.label :name, "タグ名", class: "small" %></div>
          <div class="ml-3"><%= f.text_field :name, placeholder: "タグ名" %></div>
          <div class="ml-2"><%= f.submit "新規登録", class: "form-control btn btn-success ml-5" %></div>
         <% end %>
       </div>
    </div>
</div>

app/views/admin/tags/new.html.erb
<h1>Admin::Tags#new</h1>
<p>Find me in app/views/admin/tags/new.html.erb</p>

app/views/admin/tags/show.html.erb
<div class="container pt-5">
  <div class="row">
    
    <div class="col-sm-7 mx-auto">
      <h2>タグ:　<%= @tag.name %></h2>
      
      <% unless @tag.posts.blank? %>
       <table class='table mt-3'>
          <thead>
           <th></th>
           <th>タイトル</th>
           <th>いいね数</th>
         </thead>
         <tbody>
           <% @tag.posts.each do |post| %>
           <% if post.status == "disclosure" %>
           <tr>
             <td>
                 <%= link_to post_path(post) do %>
                 <%= image_tag post.get_image, size:'50x50' %><% end %>
             </td>
             <td><%= link_to post.title, post_path(post) %></td>
             <td class=<%= "like-" + post.id.to_s %> >
             <%= render "public/likes/btn", post: post %></td>
           <% end %></tr>
           <% end %>
         </tbody>
       </table>
       <% else %>
        <p>投稿はありません</p>
       <% end %>

      <div class= "d-flex justify-content-center">
        <%#= paginate @items %>
      </div>
    </div>
    
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row mb-4">
    
    <div class="col-md-7">
      <h3 class="offset-1 my-5 text title-text">会員一覧</h3>
      <div class="row">
        <div class="col-12 mx-auto">
          

          <table class="table table-hover">
            <thead>
              <tr class="table-active text">
                <th>氏名</th>
                <th>ステータス</th>
                <th>投稿数</th>
                <th></th>
                <th></th>
              </tr>
            </thead>

              <tbody>
                <% @users.each do |user| %>
                 
                  <tr class="light-text">
                    <td class="text">
                      <%= link_to admin_user_path(user), class: "text-dark" do %>
                        <%= user.name %>
                      <% end %>
                    </td>
                    <td>
                      <%= user.job.name %>
                    </td>
                    <td>
                      <%= user.posts.count %>件
                    </td>
                  </tr>
                  
                <% end %>
              </tbody>
           </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
	    <h2 class="section-ttl text-center pb-5">ユーザーページ</h2>
	  </div>
	</div>
	<div class="row">
	  
	 <div class="col-lg-3 mt-5">
	    <table class="user_info text-center ml-5">
		     <thead>
			     <th colspan="4">登録情報</th>
		     </thead>
		     <tbody>
			     <tr>
				      <td>名前</td>
				      <td colspan="2"><%= @user.name %></td>
			     </tr>
			     <tr>
				      <td>ステータス</td>
				      <td></td>
				      <td colspan="2"><%= @user.job.name %></td>
			     </tr>
			     <tr>
				     <td>自己紹介</td>
				     <td colspan="3"><%= @user.body %></td>
			     </tr>
			     <% if @user == current_user %>
			     <tr>
				     <td>性別</td><td></td>
				     <td colspan="2"><%= @user.gender_i18n %></td>
			     </tr>
			     <tr>
				     <td>身長</td><td></td>
				     <td colspan="2"><%= @user.height %></td>
			     </tr>
			     <tr>
				     <td>体重</td><td></td>
				   <td colspan="2"><%= @user.weight %></td>
			     </tr>
			     <tr>
				     <td>悩み</td><td></td>
				     <td colspan="2"><%= @user.problem %></td>
			     </tr>
			     <% end %>
		     </tbody>
	    </table>
        

	      <div class="col-lg-3 mt-5">
	      <%# if @user.profile_image.attached? %>
	      	<%= image_tag @user.get_profile_image, size: "300x200" %>
	      <%# else %>
		   	<%#= image_tag 'no_image', size: "300x200" %>
         <%# end %>
	      </div></br>


 