config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }


  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end


  root 'public/homes#top'
  get 'about' => 'public/homes#about'


  namespace :admin do
   resources :tags
   resources :posts
   resources :jobs
   resources :users
  end
  scope module: :public do
   resources :tags

   resources :jobs
   resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
   end
   resources :targets
   resources :steps
   resources :posts do
    resources :post_tags
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
   end


  end



  #devise_for :admins
  #devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
  belongs_to :post
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments
  has_many :image_tags, dependent: :destroy

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  enum status: { secret: 0, disclosure: 1 }
  #has_many :comments
  #has_many :favorites
  has_one_attached :image
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :user
  def self.chart_date
    order(date: :asc).pluck('date', 'count').to_h
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
 has_many :post_tags, dependent: :destroy
 has_many :posts, through: :post_tags ,dependent: :destroy
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user

  enum status: { process: 0, success: 1 , failed: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :steps
  has_many :targets
  belongs_to :job, optional: true
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  enum gender: { ignore: 0, men: 1, women: 2 }
  enum status: { secret: 0, disclosure: 1 }
  #has_many :comments
  #has_many :favorites
  has_one_attached :profile_image
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  def fair_weight
  height * height * 22 / 10000
  end
  def bmi
    weight * 10000 / height / height 
  end
  def bmi25
    height * height * 25 / 10000
  end
  def bmi30
    height * height * 30 / 10000
  end
  def bmi35
    height * height * 35 / 10000
  end
  def bmi40
    height * height * 40 / 10000
  end
  def bmi18
    height * height * 37 / 20000
  end
  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @jobs = Job.all
    @job = Job.new
  end

  def new
  end

  def show
    @job = Job.find(params[:id])
  end
  def create
   @job = Job.new(job_params)
    if @job.save
     redirect_to jobs_path
    else
      render :index
    end
  end
  private
  def job_params
    params.require(:job).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%#= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.omniauthable? %>
  <%#- resource_class.omniauth_providers.each do |provider| %>
    <%#= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <%# end %>
<%# end %>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(model.errors.count, "error") %> prohibited this obj from being saved!</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom">
    <nav class="navar bg-dark text-white text-center">@Salt health promotion team</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="headber bg-secondary">
  <nav class="navar">
    <div class="container">
      <div class="row">
       <div class="col-3">
        
        <%= link_to root_path do %>
        <%= image_tag '14012023062143A.png', size: "180x100" %>
        <% end %>
       </div>

       


       <div class="col-6">
        <% if user_signed_in? %>
         <%= link_to "マイページ", user_path(current_user.id), class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "投稿一覧", posts_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ユーザー一覧", users_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-dark" %>
        <% elsif admin_signed_in? %>管理者でログイン中
         <%= link_to "投稿一覧", admin_posts_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ユーザー一覧", admin_users_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "タグ一覧", admin_tags_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ステータス一覧", admin_jobs_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-sm btn-outline-dark" %>
        <% else %>
         <%= link_to "About", about_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "投稿一覧", posts_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ユーザー一覧", users_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "新規登録", new_user_registration_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ログイン", new_user_session_path, class: "btn btn-sm btn-outline-dark" %>
        <% end %>
        </br>
       </div>

      </div>
     </div>
   </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Walking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/header' %>
    <% if flash[:notice] %>
    <div class="alert alert-light">
      <span class="ml-2"><%#= notice %></span>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="alert alert-light">
      <span class="ml-2"><%#= alert %></span>
    </div>
    <% end %>
    <main>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>